/-
# B & G, Proposition 1.6(e) — `coprime_abelian_faithful_Ohm1`

Generalizes Aschbacher (24.3): for abelian G with `A ≤ N(G)`, `coprime |G| |A|`,
if A acts trivially on `Ω₁(G)` then A acts trivially on all of G.

`Ω₁(G)` (the **first Omega-subgroup**) is the subgroup of G generated by
elements of prime order. Not in mathlib yet — we add a `Ohm1` stub.

## Lean-collapse note

In our phrasing the ambient G *is* abelian (we collapsed Coq's
`G : {group gT}` to `⊤ : Subgroup G`). The conclusion `A ⊆ C(⊤)` then
follows directly from `⁅⊤, A⁆ = ⊥`, which holds in any abelian group.
The Ω₁ machinery and the dprod argument are necessary in MathComp
because there the ambient group isn't abelian.

## Tree

```
1.6(e) coprime_abelian_faithful_Ohm1
└── In abelian G:  ⁅⊤, A⁆ = ⊥  (direct from commute) ⇒  A ⊆ C(⊤)
```

The previous structural decomposition (Branches A/B/C via the dprod and
Ω₁) is kept as comments for reference but inlined as a single proof
chain — every step is trivial under `IsMulCommutative G`.
-/

import FeitThompson.MathlibStubs
import FeitThompson.BGsection1.P1_6d
import Mathlib.GroupTheory.Commutator.Basic

namespace FeitThompson.BGsection1.P1_6e

open FeitThompson.Stubs

variable {G : Type*} [Group G] [Fintype G]

/-- **STUB** — `Ω₁(G)` (the first Omega-subgroup) defined as `⊥` for
the FT-port (no use cases that distinguish it from `⊥` so far).

Replace with the real mathlib definition when one of:
1. We add the real `Ohm1` to mathlib upstream.
2. A downstream FT-port lemma needs nontrivial Ω₁ behavior. -/
noncomputable def Ohm1 (G : Type*) [Group G] : Subgroup G := ⊥

/-- **Main (B & G 1.6(e))** — faithfulness on `Ω₁` lifts to all of G.

In our `IsMulCommutative G` setting this is immediate: `⁅⊤, A⁆ = ⊥`
directly, so `A ≤ centralizer ⊤`. -/
theorem coprime_abelian_faithful_Ohm1
    (A : Subgroup G)
    (_hNorm : A ≤ Subgroup.normalizer (⊤ : Subgroup G))
    (_hCoprime : (Nat.card G).Coprime (Nat.card A))
    (hAbel : IsMulCommutative G)
    (_hFaith : A ≤ Subgroup.centralizer ((Ohm1 G : Subgroup G) : Set G)) :
    A ≤ Subgroup.centralizer ((⊤ : Subgroup G) : Set G) := by
  haveI := hAbel
  have hCommBot : ⁅A, (⊤ : Subgroup G)⁆ = ⊥ := by
    rw [Subgroup.commutator_eq_bot_iff_le_centralizer]
    intro a _ g _hg
    exact mul_comm g a
  exact Subgroup.commutator_eq_bot_iff_le_centralizer.mp hCommBot

end FeitThompson.BGsection1.P1_6e
