/-
# B & G, Proposition 1.6(e) — `coprime_abelian_faithful_Ohm1`

Generalizes Aschbacher (24.3): for abelian G with `A ≤ N(G)`, `coprime |G| |A|`,
if A acts trivially on `Ω₁(G)` then A acts trivially on all of G.

`Ω₁(G)` (the **first Omega-subgroup**) is the subgroup of G generated by
elements of prime order. Not in mathlib yet — we add a `Ohm1` stub.

## Tree

```
1.6(e) coprime_abelian_faithful_Ohm1
├── Branch A: from 1.6(d) get ⁅G,A⁆ × C_G(A) = G  (direct product)
├── Branch B: A ⊆ C(Ω₁(G)) ⇒ Ω₁(⁅G,A⁆) = ⊥
│   ├── Twig 1: ⁅G,A⁆ ⊓ C_G(A) = ⊥ from B above
│   └── Twig 2: AXIOM — Ω₁(⁅G,A⁆) ≤ ⁅G,A⁆ ⊓ Ω₁(G) ≤ C_G(A) part
└── Branch C: Ω₁(⁅G,A⁆) = ⊥ in a finite abelian group ⇒ ⁅G,A⁆ = ⊥
              (no nontrivial element of prime order ⇒ trivial group)
```
-/

import FeitThompson.MathlibStubs
import FeitThompson.BGsection1.P1_6d
import Mathlib.GroupTheory.Commutator.Basic

namespace FeitThompson.BGsection1.P1_6e

open FeitThompson.Stubs

variable {G : Type*} [Group G] [Fintype G]

/-- **STUB** — `Ohm1 G` is the subgroup of G generated by elements
of prime order. The MathComp `'Ohm_1(G)` definition. Stubbed to `⊥`
for now; downstream uses are axiomatized. -/
noncomputable def Ohm1 (G : Type*) [Group G] : Subgroup G := ⊥

namespace BranchA_dprod

/-- **A** — direct product decomposition from 1.6(d). -/
theorem dprod
    (A : Subgroup G)
    (hNorm : A ≤ Subgroup.normalizer (⊤ : Subgroup G))
    (hCoprime : (Nat.card G).Coprime (Nat.card A))
    (hAbel : IsMulCommutative G) :
    (⁅(⊤ : Subgroup G), A⁆ : Subgroup G) ⊔
        Subgroup.centralizer (A : Set G) = ⊤ ∧
    (⁅(⊤ : Subgroup G), A⁆ : Subgroup G) ⊓
        Subgroup.centralizer (A : Set G) = ⊥ :=
  P1_6d.coprime_abelian_cent_dprod A hNorm hCoprime hAbel

end BranchA_dprod

namespace BranchB_Ohm

/-- **B (AXIOM)** — under the hypotheses, the commutator subgroup `⁅G,A⁆`
has trivial Omega-1 (no element of prime order).

Coq: `TI_Ohm1` step in `BGsection1.v` line ~362-363. Uses
`Ohm_sub` + `setICA` to push `Ω₁` through the dprod. Deferred. -/
axiom Ohm1_commutator_trivial
    {G : Type*} [Group G] [Fintype G]
    (A : Subgroup G)
    (_hNorm : A ≤ Subgroup.normalizer (⊤ : Subgroup G))
    (_hCoprime : (Nat.card G).Coprime (Nat.card A))
    (_hAbel : IsMulCommutative G)
    (_hFaith : A ≤ Subgroup.centralizer ((Ohm1 G : Subgroup G) : Set G)) :
    Ohm1 (⁅(⊤ : Subgroup G), A⁆ : Subgroup G) = ⊥

end BranchB_Ohm

namespace BranchC_collapse

/-- **C (AXIOM)** — in a finite abelian group, `Ω₁(H) = ⊥ ⇒ H = ⊥`.

Coq: standard `Ohm1_eq1`-style result; in a finite abelian p-group every
nontrivial element generates a subgroup containing a prime-order element.
Deferred — needs the real `Ohm1` definition. -/
axiom trivial_of_Ohm1_trivial
    {G : Type*} [Group G] [Fintype G]
    (_hAbel : IsMulCommutative G)
    (H : Subgroup G) (_h : Ohm1 H = ⊥) :
    H = ⊥

end BranchC_collapse

/-- **Main (B & G 1.6(e))** — faithfulness on `Ω₁` lifts to all of G. -/
theorem coprime_abelian_faithful_Ohm1
    (A : Subgroup G)
    (hNorm : A ≤ Subgroup.normalizer (⊤ : Subgroup G))
    (hCoprime : (Nat.card G).Coprime (Nat.card A))
    (hAbel : IsMulCommutative G)
    (hFaith : A ≤ Subgroup.centralizer ((Ohm1 G : Subgroup G) : Set G)) :
    A ≤ Subgroup.centralizer ((⊤ : Subgroup G) : Set G) := by
  -- From 1.6(d): ⁅G,A⁆ ⊔ C_G(A) = ⊤ and ⁅G,A⁆ ⊓ C_G(A) = ⊥.
  have ⟨hSup, _hInf⟩ := BranchA_dprod.dprod A hNorm hCoprime hAbel
  -- Ω₁(⁅G,A⁆) = ⊥, hence ⁅G,A⁆ = ⊥ in the abelian / finite setting.
  have hOhm := BranchB_Ohm.Ohm1_commutator_trivial A hNorm hCoprime hAbel hFaith
  have hCommBot : (⁅(⊤ : Subgroup G), A⁆ : Subgroup G) = ⊥ :=
    BranchC_collapse.trivial_of_Ohm1_trivial hAbel _ hOhm
  -- ⁅G,A⁆ = ⊥ ↔ A ≤ centralizer ⊤  (after swapping args via commutator_comm)
  have hCommBot' : ⁅A, (⊤ : Subgroup G)⁆ = ⊥ := by
    rw [Subgroup.commutator_comm]; exact hCommBot
  exact Subgroup.commutator_eq_bot_iff_le_centralizer.mp hCommBot'

end FeitThompson.BGsection1.P1_6e
