/-
Port of `BGsection1.v` from `math-comp/odd-order`.

Upstream: papers/odd-order/BGsection1.v (1335 lines, 89 declarations).

# Scope of upstream file (B & G = Bender-Glauberman)

| Kind         | Count |
| ------------ | ----- |
| Definitions  | 14    |
| Notations    | 12    |
| Lemmas       | 35    |
| Propositions | 20    |
| Theorems     |  5    |
| Corollaries  |  3    |

Covers: B & G 1.3-1.4, 1.6, 1.8-1.21, Gorenstein 8.1.3, Gorenstein 2.8.1.

# Approach

Build on `FeitThompson.Stubs` for the finite-group-theory concepts that
mathlib does not yet have (Fitting subgroup, p-core, min-normal, Hall,
chief factors). See `MathlibStubs.lean` for the stub catalog.

# Status

🚧 In-progress port. Each lemma marked one of:

- `STATED`   — translates cleanly into Lean. Proof = `sorry`.
- `BLOCKED`  — needs a stub we haven't added yet, or a mathlib gap.
- `PROVED`   — actually proved end-to-end (rare so far).
-/

import FeitThompson.MathlibStubs

namespace FeitThompson.BGsection1

open FeitThompson.Stubs

variable {G : Type*} [Group G]

-- ════════════════════════════════════════════════════════════════════
-- §Definitions  (BGsection1.v lines 61-122)
-- ════════════════════════════════════════════════════════════════════

/-- `plength_1 p G`: the upper p-series of G has length ≤ 1. -/
def plength_1 (p : ℕ) : Prop := pCoreLayer p G 3 = ⊤

/-- `p_elt_gen p G`: subgroup of G generated by its p-elements. -/
def pEltGen (p : ℕ) : Subgroup G :=
  Subgroup.closure { x | IsPGroup p (Subgroup.zpowers x) }

/-- `p_constrained p G`: for every Sylow p-subgroup P of O_{p',p}(G),
the centralizer of P is contained in O_{p',p}(G). -/
def pConstrained (p : ℕ) : Prop :=
  ∀ P : Subgroup G, IsPGroup p P → P ≤ pCoreLayer p G 2 →
    Subgroup.centralizer (P : Set G) ≤ pCoreLayer p G 2

/-- `p_abelian_constrained p G`: every normal abelian subgroup of a Sylow
p-subgroup lies in O_{p',p}(G). -/
def pAbelianConstrained (p : ℕ) : Prop :=
  ∀ S A : Subgroup G, IsPGroup p S → IsMulCommutative A →
    A.Normal → A ≤ S → A ≤ pCoreLayer p G 2

/-- `generated_by gp E`: E is generated by some set of subgroups satisfying `gp`. -/
def generatedBy (gp : Subgroup G → Prop) (E : Subgroup G) : Prop :=
  ∃ S : Set (Subgroup G), (∀ H ∈ S, gp H) ∧
    Subgroup.closure (⋃ H ∈ S, (H : Set G)) = E

/-- `norm_abelian D A`: A is abelian and normalized by D. -/
def normAbelian (D : Subgroup G) (A : Subgroup G) : Prop :=
  D ≤ Subgroup.normalizer A ∧ IsMulCommutative A

/-- `p_norm_abelian p D A`: A is an abelian p-group normalized by D. -/
def pNormAbelian (p : ℕ) (D A : Subgroup G) : Prop :=
  IsPGroup p A ∧ normAbelian D A

/-- `'L_[G](X)` (Puig successor): the group generated by abelian subgroups
of G normalized by X. -/
noncomputable def puigSucc (D E : Subgroup G) : Subgroup G :=
  Subgroup.closure (⋃ A ∈ { A : Subgroup G | A ≤ D ∧ normAbelian E A }, (A : Set G))

-- ════════════════════════════════════════════════════════════════════
-- §BGsection1 — Lemmas, Propositions, Theorems
-- ════════════════════════════════════════════════════════════════════

/-- **STATED** — B & G, Lemma 1.1, first part.

A solvable minimal-normal subgroup is elementary abelian.

UPSTREAM:
  `Lemma minnormal_solvable_abelem gT (M G : {group gT}) :
     minnormal M G -> solvable M -> is_abelem M.`
-/
theorem minnormal_solvable_abelem
    (M : Subgroup G) (_hMin : MinNormal M) (_hSol : IsSolvable M) :
    IsAbelem M := by
  sorry

/-- **BLOCKED** — B & G, Lemma 1.1, second part / Lemma 1.2.

A solvable minimal-normal M of G lies in the center of F(G).

UPSTREAM:
  `Lemma minnormal_solvable_Fitting_center gT (M G : {group gT}) :
     minnormal M G ->  M \subset G -> solvable M -> M \subset 'Z('F(G)).`
-/
theorem minnormal_solvable_Fitting_center
    (M : Subgroup G) (_hMin : MinNormal M) (_hSol : IsSolvable M) :
    M ≤ FittingSubgroup G ⊓
      Subgroup.centralizer ((FittingSubgroup G : Subgroup G) : Set G) := by
  -- Upstream phrasing `M ≤ 'Z('F(G))` is "M is contained in the center of
  -- F(G)". In mathlib idiom that's `M ≤ F(G) ⊓ C_G(F(G))` (the elements
  -- of F(G) that commute with all of F(G), viewed inside G).
  sorry

/-- **STATED** — B & G, Proposition 1.3 (P. Hall).

In a solvable group, the centralizer of the Fitting subgroup is contained
in the Fitting subgroup itself.

UPSTREAM:
  `Proposition cent_sub_Fitting gT (G : {group gT}) :
     solvable G -> 'C_G('F(G)) \subset 'F(G).`

This is the flagship lemma of §1 — the rest of the chapter uses it
repeatedly. -/
theorem cent_sub_Fitting (_hG : IsSolvable G) :
    Subgroup.centralizer ((FittingSubgroup G : Subgroup G) : Set G)
      ≤ FittingSubgroup G := by
  sorry

/-- **STATED** — B & G, Proposition 1.4 (internal action).

If A normalizes G with coprime orders, G is solvable, and `C_A(G) = 1`,
then `C_A(F(G)) = 1`.

UPSTREAM:
  `Proposition coprime_trivg_cent_Fitting gT (A G : {group gT}) :
     A \subset 'N(G) -> coprime #|G| #|A| -> solvable G ->
     'C_A(G) = 1 -> 'C_A('F(G)) = 1.`
-/
theorem coprime_trivg_cent_Fitting
    [Fintype G] (A : Subgroup G)
    (_hNorm : A ≤ Subgroup.normalizer (⊤ : Subgroup G))
    (_hCoprime : (Nat.card G).Coprime (Nat.card A))
    (_hSol : IsSolvable G)
    (_hCentTrivial : A ⊓ Subgroup.centralizer ((⊤ : Subgroup G) : Set G) = ⊥) :
    A ⊓ Subgroup.centralizer ((FittingSubgroup G : Subgroup G) : Set G) = ⊥ := by
  sorry

end FeitThompson.BGsection1
