/-
Port of `BGsection1.v` from `math-comp/odd-order`.

Upstream: papers/odd-order/BGsection1.v (1335 lines, 89 declarations).

# Scope of upstream file (B & G = Bender-Glauberman)

| Kind         | Count |
| ------------ | ----- |
| Definitions  | 14    |
| Notations    | 12    |
| Lemmas       | 35    |
| Propositions | 20    |
| Theorems     |  5    |
| Corollaries  |  3    |

Covers: B & G 1.3-1.4, 1.6, 1.8-1.21, Gorenstein 8.1.3, Gorenstein 2.8.1.

# Approach

Build on `FeitThompson.Stubs` for the finite-group-theory concepts that
mathlib does not yet have (Fitting subgroup, p-core, min-normal, Hall,
chief factors). See `MathlibStubs.lean` for the stub catalog.

# Status

🚧 In-progress port. Each lemma marked one of:

- `STATED`   — translates cleanly into Lean. Proof = `sorry`.
- `BLOCKED`  — needs a stub we haven't added yet, or a mathlib gap.
- `PROVED`   — actually proved end-to-end (rare so far).
-/

import FeitThompson.MathlibStubs
import FeitThompson.BGsection1.L1_1
import FeitThompson.BGsection1.L1_2
import FeitThompson.BGsection1.P1_3
import FeitThompson.BGsection1.P1_4
import FeitThompson.BGsection1.P1_6
import FeitThompson.BGsection1.P1_6d
import FeitThompson.BGsection1.P1_6e
import FeitThompson.BGsection1.P1_8
import FeitThompson.BGsection1.P1_9_base
import FeitThompson.BGsection1.P1_9
import FeitThompson.BGsection1.P1_10
import FeitThompson.BGsection1.T1_11
import FeitThompson.BGsection1.C1_12
import FeitThompson.BGsection1.T1_13
import Mathlib.GroupTheory.Commutator.Basic
import Mathlib.GroupTheory.Frattini
import Mathlib.GroupTheory.Nilpotent

namespace FeitThompson.BGsection1

open FeitThompson.Stubs

variable {G : Type*} [Group G]

-- ════════════════════════════════════════════════════════════════════
-- §Definitions  (BGsection1.v lines 61-122)
-- ════════════════════════════════════════════════════════════════════

/-- `plength_1 p G`: the upper p-series of G has length ≤ 1. -/
def plength_1 (p : ℕ) : Prop := pCoreLayer p G 3 = ⊤

/-- `p_elt_gen p G`: subgroup of G generated by its p-elements. -/
def pEltGen (p : ℕ) : Subgroup G :=
  Subgroup.closure { x | IsPGroup p (Subgroup.zpowers x) }

/-- `p_constrained p G`: for every Sylow p-subgroup P of O_{p',p}(G),
the centralizer of P is contained in O_{p',p}(G). -/
def pConstrained (p : ℕ) : Prop :=
  ∀ P : Subgroup G, IsPGroup p P → P ≤ pCoreLayer p G 2 →
    Subgroup.centralizer (P : Set G) ≤ pCoreLayer p G 2

/-- `p_abelian_constrained p G`: every normal abelian subgroup of a Sylow
p-subgroup lies in O_{p',p}(G). -/
def pAbelianConstrained (p : ℕ) : Prop :=
  ∀ S A : Subgroup G, IsPGroup p S → IsMulCommutative A →
    A.Normal → A ≤ S → A ≤ pCoreLayer p G 2

/-- `generated_by gp E`: E is generated by some set of subgroups satisfying `gp`. -/
def generatedBy (gp : Subgroup G → Prop) (E : Subgroup G) : Prop :=
  ∃ S : Set (Subgroup G), (∀ H ∈ S, gp H) ∧
    Subgroup.closure (⋃ H ∈ S, (H : Set G)) = E

/-- `norm_abelian D A`: A is abelian and normalized by D. -/
def normAbelian (D : Subgroup G) (A : Subgroup G) : Prop :=
  D ≤ Subgroup.normalizer A ∧ IsMulCommutative A

/-- `p_norm_abelian p D A`: A is an abelian p-group normalized by D. -/
def pNormAbelian (p : ℕ) (D A : Subgroup G) : Prop :=
  IsPGroup p A ∧ normAbelian D A

/-- `'L_[G](X)` (Puig successor): the group generated by abelian subgroups
of G normalized by X. -/
noncomputable def puigSucc (D E : Subgroup G) : Subgroup G :=
  Subgroup.closure (⋃ A ∈ { A : Subgroup G | A ≤ D ∧ normAbelian E A }, (A : Set G))

/-- `p_stable p G`: a representation-theoretic Hall-Higman-style condition.

In B & G:
  `∀ P A, p-group P → O_p'(G) * P ⊲ G → p-subgroup of N_G(P) (A) →
     [P, A, A] = 1 → A · C_G(P) ⊆ O_p(N_G(P) / C_G(P))`

**STUB** — the conclusion involves `pCore` applied to a *quotient* of a
*subgroup*, which requires viewing subgroups and quotients as groups in
their own right (a routine but bulky construction). We stub the full
condition for now. -/
def pStable (_p : ℕ) (_G : Type*) [Group _G] : Prop := True  -- STUB

/-- Puig iteration: `puigAt n D G` is the n-th Puig group with respect to D. -/
noncomputable def puigAt : ℕ → Subgroup G → Subgroup G
  | 0,     _ => ⊥
  | n + 1, D => puigSucc D (puigAt n D)

/-- `'L_*(G)` — limit of the Puig series (lower limit). Defined as `puigAt`
applied to a large enough index. -/
noncomputable def puigInf [Fintype G] : Subgroup G :=
  puigAt (2 * Nat.card G) ⊤

/-- `'L(G)` — the Puig subgroup (upper limit). -/
noncomputable def puig [Fintype G] : Subgroup G :=
  puigSucc ⊤ puigInf

-- ════════════════════════════════════════════════════════════════════
-- §BGsection1 — Lemmas, Propositions, Theorems
-- ════════════════════════════════════════════════════════════════════

/-- **PROVED (modulo leaf sorries)** — B & G, Lemma 1.1, first part.

A solvable minimal-normal subgroup is elementary abelian.

Decomposed into a proof tree in `FeitThompson.BGsection1.L1_1`:
  - Branch A: M is abelian (4 twigs)
  - Branch B: M has prime exponent (4 twigs)
  - Top-level: assembles into `IsAbelem M`

UPSTREAM:
  `Lemma minnormal_solvable_abelem gT (M G : {group gT}) :
     minnormal M G -> solvable M -> is_abelem M.`
-/
theorem minnormal_solvable_abelem
    (M : Subgroup G) [Finite M] (hMin : MinNormal M) (hSol : IsSolvable M) :
    IsAbelem M :=
  L1_1.minnormal_solvable_abelem M hMin hSol

/-- **BLOCKED** — B & G, Lemma 1.1, second part / Lemma 1.2.

A solvable minimal-normal M of G lies in the center of F(G).

UPSTREAM:
  `Lemma minnormal_solvable_Fitting_center gT (M G : {group gT}) :
     minnormal M G ->  M \subset G -> solvable M -> M \subset 'Z('F(G)).`
-/
theorem minnormal_solvable_Fitting_center
    (M : Subgroup G) [Finite M] (hMin : MinNormal M) (hSol : IsSolvable M) :
    M ≤ FittingSubgroup G ⊓
      Subgroup.centralizer ((FittingSubgroup G : Subgroup G) : Set G) :=
  L1_2.minnormal_solvable_Fitting_center M hMin hSol

/-- **STATED** — B & G, Proposition 1.3 (P. Hall).

In a solvable group, the centralizer of the Fitting subgroup is contained
in the Fitting subgroup itself.

UPSTREAM:
  `Proposition cent_sub_Fitting gT (G : {group gT}) :
     solvable G -> 'C_G('F(G)) \subset 'F(G).`

This is the flagship lemma of §1 — the rest of the chapter uses it
repeatedly. -/
theorem cent_sub_Fitting (hG : IsSolvable G) :
    Subgroup.centralizer ((FittingSubgroup G : Subgroup G) : Set G)
      ≤ FittingSubgroup G :=
  P1_3.cent_sub_Fitting hG

/-- **STATED** — B & G, Proposition 1.4 (internal action).

If A normalizes G with coprime orders, G is solvable, and `C_A(G) = 1`,
then `C_A(F(G)) = 1`.

UPSTREAM:
  `Proposition coprime_trivg_cent_Fitting gT (A G : {group gT}) :
     A \subset 'N(G) -> coprime #|G| #|A| -> solvable G ->
     'C_A(G) = 1 -> 'C_A('F(G)) = 1.`
-/
theorem coprime_trivg_cent_Fitting
    [Fintype G] (A : Subgroup G)
    (hNorm : A ≤ Subgroup.normalizer (⊤ : Subgroup G))
    (hCoprime : (Nat.card G).Coprime (Nat.card A))
    (hSol : IsSolvable G)
    (hCentTrivial : A ⊓ Subgroup.centralizer ((⊤ : Subgroup G) : Set G) = ⊥) :
    A ⊓ Subgroup.centralizer ((FittingSubgroup G : Subgroup G) : Set G) = ⊥ :=
  P1_4.coprime_trivg_cent_Fitting A hNorm hCoprime hSol hCentTrivial

/-- **STATED** — B & G, Proposition 1.6(a) (`coprime_cent_prod`).

`A ⊆ N(G) ∧ coprime |G| |A| ∧ solvable G → [G,A] · C_G(A) = G`.

UPSTREAM:
  `Proposition coprime_cent_prod gT (A G : {group gT}) :
     A \subset 'N(G) -> coprime #|G| #|A| -> solvable G ->
     [~: G, A] * 'C_G(A) = G.`
-/
theorem coprime_cent_prod
    [Fintype G] (A : Subgroup G)
    (hNorm : A ≤ Subgroup.normalizer (⊤ : Subgroup G))
    (hCoprime : (Nat.card G).Coprime (Nat.card A))
    (hSol : IsSolvable G) :
    (⁅(⊤ : Subgroup G), A⁆ : Subgroup G) ⊔
      Subgroup.centralizer (A : Set G) = ⊤ :=
  P1_6.coprime_cent_prod A hNorm hCoprime hSol

/-- **STATED** — B & G, Proposition 1.6(b) (`coprime_commGid`).

Under the same hypotheses, `[G,A,A] = [G,A]`.

UPSTREAM:
  `Proposition coprime_commGid gT (A G : {group gT}) :
     A \subset 'N(G) -> coprime #|G| #|A| -> solvable G ->
     [~: G, A, A] = [~: G, A].`
-/
theorem coprime_commGid
    [Fintype G] (A : Subgroup G)
    (hNorm : A ≤ Subgroup.normalizer (⊤ : Subgroup G))
    (hCoprime : (Nat.card G).Coprime (Nat.card A))
    (hSol : IsSolvable G) :
    ⁅(⁅(⊤ : Subgroup G), A⁆ : Subgroup G), A⁆ = ⁅(⊤ : Subgroup G), A⁆ :=
  P1_6.coprime_commGid A hNorm hCoprime hSol

/-- **STATED** — B & G, Proposition 1.6(c) (`coprime_commGG1P`).

If furthermore `[G,A,A] = 1` then `A ⊆ C(G)`.

UPSTREAM:
  `Proposition coprime_commGG1P gT (A G : {group gT}) :
     A \subset 'N(G) -> coprime #|G| #|A| -> solvable G ->
     [~: G, A, A] = 1 -> A \subset 'C(G).`
-/
theorem coprime_commGG1P
    [Fintype G] (A : Subgroup G)
    (hNorm : A ≤ Subgroup.normalizer (⊤ : Subgroup G))
    (hCoprime : (Nat.card G).Coprime (Nat.card A))
    (hSol : IsSolvable G)
    (hVanish : ⁅(⁅(⊤ : Subgroup G), A⁆ : Subgroup G), A⁆ = ⊥) :
    A ≤ Subgroup.centralizer ((⊤ : Subgroup G) : Set G) :=
  P1_6.coprime_commGG1P A hNorm hCoprime hSol hVanish

/-- **STATED** — B & G, Proposition 1.8 / Aschbacher 24.1 (`coprime_cent_Phi`).

If G is a p-group, |A| is coprime to |G|, and `[G,A] ⊆ Φ(G)`, then `A ⊆ C(G)`.

UPSTREAM:
  `Proposition coprime_cent_Phi gT p (A G : {group gT}) :
     p.-group G -> coprime #|G| #|A| -> [~: G, A] \subset 'Phi(G) ->
     A \subset 'C(G).`

This one uses mathlib's real `frattini` definition — no stub needed for
the Frattini subgroup, only for the rest of the apparatus. -/
theorem coprime_cent_Phi
    [Fintype G] (p : ℕ) (A : Subgroup G)
    (hG : IsPGroup p (⊤ : Subgroup G))
    (hCoprime : (Nat.card G).Coprime (Nat.card A))
    (hCommInPhi : (⁅(⊤ : Subgroup G), A⁆ : Subgroup G) ≤ frattini G) :
    A ≤ Subgroup.centralizer ((⊤ : Subgroup G) : Set G) :=
  P1_8.coprime_cent_Phi p A hG hCoprime hCommInPhi

/-- **STATED** — B & G, Proposition 1.6(d) (`coprime_abelian_cent_dprod`).

In the abelian setting, the join from 1.6(a) refines to an internal direct
product: `⁅G,A⁆ × C_G(A) = G`. We expose both halves (sup = ⊤ and inf = ⊥).

UPSTREAM:
  `Proposition coprime_abelian_cent_dprod gT (A G : {group gT}) :
     A \subset 'N(G) -> coprime #|G| #|A| -> abelian G ->
     [~: G, A] \x 'C_G(A) = G.`
-/
theorem coprime_abelian_cent_dprod
    [Fintype G] (A : Subgroup G)
    (hNorm : A ≤ Subgroup.normalizer (⊤ : Subgroup G))
    (hCoprime : (Nat.card G).Coprime (Nat.card A))
    (hAbel : IsMulCommutative G) :
    (⁅(⊤ : Subgroup G), A⁆ : Subgroup G) ⊔
        Subgroup.centralizer (A : Set G) = ⊤ ∧
    (⁅(⊤ : Subgroup G), A⁆ : Subgroup G) ⊓
        Subgroup.centralizer (A : Set G) = ⊥ :=
  P1_6d.coprime_abelian_cent_dprod A hNorm hCoprime hAbel

/-- **STATED** — B & G, Proposition 1.6(e) (`coprime_abelian_faithful_Ohm1`).

Generalizes Aschbacher (24.3): in the abelian coprime setting, faithful
action on `Ω₁(G)` lifts to faithful action on G.

UPSTREAM:
  `Proposition coprime_abelian_faithful_Ohm1 gT (A G : {group gT}) :
     A \subset 'N(G) -> coprime #|G| #|A| -> abelian G ->
     A \subset 'C('Ohm_1(G)) -> A \subset 'C(G).`
-/
theorem coprime_abelian_faithful_Ohm1
    [Fintype G] (A : Subgroup G)
    (hNorm : A ≤ Subgroup.normalizer (⊤ : Subgroup G))
    (hCoprime : (Nat.card G).Coprime (Nat.card A))
    (hAbel : IsMulCommutative G)
    (hFaith : A ≤ Subgroup.centralizer ((P1_6e.Ohm1 G : Subgroup G) : Set G)) :
    A ≤ Subgroup.centralizer ((⊤ : Subgroup G) : Set G) :=
  P1_6e.coprime_abelian_faithful_Ohm1 A hNorm hCoprime hAbel hFaith

/-- **STATED** — B & G, Proposition 1.9 base case (`stable_factor_cent`).

If `A ⊆ C(H)`, the chain is A-stable, A and G have coprime orders, and G is
solvable, then A acts trivially on G.

UPSTREAM:
  `Proposition stable_factor_cent gT (A G H : {group gT}) :
     A \subset 'C(H) -> stable_factor A H G ->
     coprime #|G| #|A| -> solvable G ->
     A \subset 'C(G).`
-/
theorem stable_factor_cent
    [Fintype G] (A H : Subgroup G)
    (hStable : P1_9_base.IsStableFactor A H)
    (hCAH : A ≤ Subgroup.centralizer (H : Set G))
    (hCoprime : (Nat.card G).Coprime (Nat.card A))
    (hSol : IsSolvable G) :
    A ≤ Subgroup.centralizer ((⊤ : Subgroup G) : Set G) :=
  P1_9_base.stable_factor_cent A H hStable hCAH hCoprime hSol

/-- **STATED** — B & G, Proposition 1.9 (`stable_series_cent`).

Iterates 1.9 base down an A-stable series.

UPSTREAM:
  `Proposition stable_series_cent gT (A G : {group gT}) s :
     last 1%G s :=: G -> (A.-stable).-series 1%G s ->
     coprime #|G| #|A| -> solvable G ->
     A \subset 'C(G).`
-/
theorem stable_series_cent
    [Fintype G] (A : Subgroup G) (s : List (Subgroup G))
    (hStable : P1_9.IsAStableSeries A s)
    (hCoprime : (Nat.card G).Coprime (Nat.card A))
    (hSol : IsSolvable G) :
    A ≤ Subgroup.centralizer ((⊤ : Subgroup G) : Set G) :=
  P1_9.stable_series_cent A s hStable hCoprime hSol

/-- **STATED** — B & G, Proposition 1.10 (`coprime_nil_faithful_cent_stab`).

For nilpotent G with A acting and `C := C_G(A)` satisfying `C_G(C) ≤ C`,
the action is trivial.

UPSTREAM:
  `Proposition coprime_nil_faithful_cent_stab gT (A G : {group gT}) :
     A \subset 'N(G) -> coprime #|G| #|A| -> nilpotent G ->
     let C := 'C_G(A) in 'C_G(C) \subset C -> A \subset 'C(G).`
-/
theorem coprime_nil_faithful_cent_stab
    [Fintype G] (A : Subgroup G)
    (hNorm : A ≤ Subgroup.normalizer (⊤ : Subgroup G))
    (hCoprime : (Nat.card G).Coprime (Nat.card A))
    (hNil : Group.IsNilpotent G)
    (hSelfCent : Subgroup.centralizer
        ((Subgroup.centralizer (A : Set G) : Subgroup G) : Set G)
      ≤ Subgroup.centralizer (A : Set G)) :
    A ≤ Subgroup.centralizer ((⊤ : Subgroup G) : Set G) :=
  P1_10.coprime_nil_faithful_cent_stab A hNorm hCoprime hNil hSelfCent

/-- **STATED** — B & G, Theorem 1.11 (`coprime_odd_faithful_Ohm1`).

For an odd-order p-group G with A normalizing G and `coprime |G| |A|`,
faithful action of A on `Ω₁(G)` implies faithful action on G.

UPSTREAM:
  `Theorem coprime_odd_faithful_Ohm1 gT p (A G : {group gT}) :
     p.-group G -> A \subset 'N(G) -> coprime #|G| #|A| -> odd #|G| ->
     A \subset 'C('Ohm_1(G)) -> A \subset 'C(G).`
-/
theorem coprime_odd_faithful_Ohm1
    [Fintype G] (p : ℕ) (A : Subgroup G)
    (hG : IsPGroup p (⊤ : Subgroup G))
    (hNorm : A ≤ Subgroup.normalizer (⊤ : Subgroup G))
    (hCoprime : (Nat.card G).Coprime (Nat.card A))
    (hOdd : Odd (Nat.card G))
    (hFaith : A ≤ Subgroup.centralizer ((P1_6e.Ohm1 G : Subgroup G) : Set G)) :
    A ≤ Subgroup.centralizer ((⊤ : Subgroup G) : Set G) :=
  T1_11.coprime_odd_faithful_Ohm1 p A hG hNorm hCoprime hOdd hFaith

/-- **STATED** — B & G, Corollary 1.12 (`coprime_odd_faithful_cent_abelem`).

For an elementary abelian p-subgroup E of an odd-order p-group G with A
acting coprimely, if A centralizes the p-torsion of `C_G(E)`, then
A centralizes G. Direct corollary of 1.11.

UPSTREAM:
  `Corollary coprime_odd_faithful_cent_abelem gT p (A G E : {group gT}) :
     E \in 'E_p(G) -> p.-group G ->
     A \subset 'N(G) -> coprime #|G| #|A| -> odd #|G| ->
     A \subset 'C('Ldiv_p('C_G(E))) -> A \subset 'C(G).`
-/
theorem coprime_odd_faithful_cent_abelem
    [Fintype G] (p : ℕ) (A E : Subgroup G)
    (hE_le_G : E ≤ ⊤)
    (hE_abelem : IsAbelem E)
    (hG : IsPGroup p (⊤ : Subgroup G))
    (hNorm : A ≤ Subgroup.normalizer (⊤ : Subgroup G))
    (hCoprime : (Nat.card G).Coprime (Nat.card A))
    (hOdd : Odd (Nat.card G))
    (hFaith : A ≤ Subgroup.centralizer
        ((C1_12.Ldiv_p p (Subgroup.centralizer (E : Set G)) : Subgroup G) : Set G)) :
    A ≤ Subgroup.centralizer ((⊤ : Subgroup G) : Set G) :=
  C1_12.coprime_odd_faithful_cent_abelem p A E hE_le_G hE_abelem hG hNorm
    hCoprime hOdd hFaith

/-- **STATED** — B & G, Theorem 1.13 (`critical_odd`, Thompson critical subgroup).

For an odd-order nontrivial p-group, there exists a characteristic subgroup
H with five strong properties (nilpotency class ≤ 2, exponent p, …).

UPSTREAM:
  `Theorem critical_odd gT p (G : {group gT}) :
     p.-group G -> odd #|G| -> G :!=: 1 ->
     {H : {group gT} |
        [/\ H \char G, [~: H, G] \subset 'Z(H), nil_class H <= 2,
            exponent H = p & p.-group 'C(H | [Aut G])]}.`
-/
theorem critical_odd
    [Fintype G] (p : ℕ) (hG : IsPGroup p (⊤ : Subgroup G))
    (hOdd : Odd (Nat.card G))
    (hNT : (⊤ : Subgroup G) ≠ ⊥) :
    ∃ H : Subgroup G, T1_13.IsCritical p H :=
  T1_13.critical_odd p hG hOdd hNT

end FeitThompson.BGsection1
