import Mathlib
import FiniteSimpleGroups.Basic

/-!
# Family 5: The 26 Sporadic Simple Groups

The "leftovers": 26 specific finite simple groups that don't fit any infinite
family. Discovered between 1861 (Mathieu groups) and 1980 (the Monster's
existence proven by Griess).

Twenty of the 26 are **subquotients of the Monster** (`M`) — these are called
the "Happy Family." The remaining 6 are the **Pariahs**: `J_1`, `J_3`, `J_4`,
`O'N`, `Ru`, `Ly`.

## The full list, by discoverer / family

### Mathieu groups (1861-1873) — five

| Group | Order | Acting on |
|-------|-------|-----------|
| `M_11` | 7,920 | 11 points, 4-transitively |
| `M_12` | 95,040 | 12 points, 5-transitively |
| `M_22` | 443,520 | 22 points, 3-transitively |
| `M_23` | 10,200,960 | 23 points, 4-transitively |
| `M_24` | 244,823,040 | 24 points, 5-transitively |

The only 4- and 5-transitive groups other than `S_n`/`A_n`. Mathlib has
**skeletal** work on these in `Mathlib.GroupTheory.SpecificGroups.Mathieu`
(check existence in v4.29.1; often a `sorry`-heavy WIP).

### Janko groups (1965-1976) — four

| Group | Order | Notes |
|-------|-------|-------|
| `J_1` | 175,560 | Janko 1965 — first "new" sporadic after Mathieu, breaking the 92-year drought. **Pariah.** |
| `J_2 = HJ` (Hall-Janko) | 604,800 | Subquotient of Monster. |
| `J_3 = HJM` | 50,232,960 | **Pariah.** |
| `J_4` | ~10^19 (huge) | **Pariah.** |

### Conway groups (1968) — three

| Group | Order | Source |
|-------|-------|--------|
| `Co_1` | ~4 × 10^18 | Automorphisms of Leech lattice / center |
| `Co_2` | 42,305,421,312,000 | Stabilizer of a type-2 vector |
| `Co_3` | 495,766,656,000 | Stabilizer of a type-3 vector |

All from John Conway's work on the Leech lattice (the densest packing of
spheres in 24 dimensions).

### Fischer groups (1971) — three

| Group | Order | Notes |
|-------|-------|-------|
| `Fi_22` | 64,561,751,654,400 | 3-transposition group |
| `Fi_23` | ~4 × 10^18 | 3-transposition group |
| `Fi_24'` | ~1.25 × 10^21 | Derived subgroup of `Fi_24`; the `Fi_24` is itself not simple |

### The Monster and its retinue (1973-1980)

| Group | Order | Discovered by |
|-------|-------|---------------|
| `M` (Monster / Friendly Giant) | ~8 × 10^53 | Fischer-Griess 1973 (conjectured), Griess 1980 (construction) |
| `B` (Baby Monster) | ~4 × 10^33 | Fischer 1973 |
| `Th` (Thompson) | ~9 × 10^16 | Thompson 1976 |
| `HN` (Harada-Norton) | 273,030,912,000,000 | Harada / Norton 1973 |
| `He` (Held) | 4,030,387,200 | Held 1969 |

### Pariahs (full list)

Not subquotients of the Monster:
`J_1` (1965), `J_3` (1976), `J_4` (1976/1980), `O'N` (O'Nan, 1973), `Ru` (Rudvalis, 1973), `Ly` (Lyons, 1972/Sims).

| Group | Order |
|-------|-------|
| `O'N` (O'Nan) | 460,815,505,920 |
| `Ru` (Rudvalis) | 145,926,144,000 |
| `Ly` (Lyons) | ~5 × 10^16 |

### Remaining of the 26: McLaughlin, Suzuki sporadic, Higman-Sims

| Group | Order | Notes |
|-------|-------|-------|
| `McL` (McLaughlin) | 898,128,000 | Subquotient of `Co_1` |
| `Suz` (Suzuki sporadic — **not** the Suzuki Lie-type group) | 448,345,497,600 | |
| `HS` (Higman-Sims) | 44,352,000 | |

## Construction status

Most sporadic groups don't have a clean closed-form construction. They're
typically defined as:
* Stabilizers in a known geometric / combinatorial structure (Leech lattice,
  Steiner system `S(5,8,24)`, the Monster's 196,883-dim representation, etc.)
* Automorphism groups of specific graphs (`HS` from the Higman-Sims graph)
* Subgroups generated by specific matrices acting on specific modules

**Status in mathlib (v4.29.1):** Essentially none of the sporadics are
constructed. This file lists them as opaque types for naming purposes only.
-/

namespace FiniteSimpleGroups
namespace Sporadics

/-! ### Mathieu groups -/
opaque M11 : Type
opaque M12 : Type
opaque M22 : Type
opaque M23 : Type
opaque M24 : Type

/-! ### Janko groups -/
opaque J1 : Type
opaque J2 : Type
opaque J3 : Type
opaque J4 : Type

/-! ### Conway groups -/
opaque Co1 : Type
opaque Co2 : Type
opaque Co3 : Type

/-! #### Conway-group simplicity (axiom, cited)

The Conway groups are the first sporadics in this scaffold to carry an explicit
simplicity claim, seeded by an existing (partial) Lean formalization.

**External evidence.** Erik van der Plas, *Formalisation of the Finite Simple
Conway Groups in Lean*, MSc thesis, Utrecht University, 2024 (advisor
J. M. Commelin).
- Handle: <https://studenttheses.uu.nl/handle/20.500.12932/46756>
- Local PDF: `~/src/lean-refs/papers/conway-groups-lean-thesis.pdf`
- Lean source (mathlib fork): `erikvdplas/mathlib4`,
  `Mathlib/GroupTheory/SpecificGroups/Conway.lean` +
  `Mathlib/GroupTheory/IntegralLattice/Leech/{Basic,Cross}.lean`.
  Local clone: `~/src/lean-refs/conway-vdplas/`.

That work defines `Conway₀ := IntegralLatticeAut Λ` (automorphisms of the Leech
lattice `Λ`) and `Conway₁ := Conway₀ ⧸ center`, and proves simplicity via the
**Iwasawa criterion** — the same engine mathlib uses for `Aₙ`.

**Why axiom, not dependency (decided 2026-05-28).** The formalization is
in-progress: ~18 `sorry`s, including `exists_leech` (the Leech lattice's very
existence) and the `perfect` / `quasipreprimitive` lemmas the `simple` instance
rests on; only `Co0`/`Co1` are touched, `Co2`/`Co3` are untouched. Taking it as
a Lake dependency would launder those `sorry`s into our trusted base — strictly
*less* honest than an explicit, attributed axiom. So we assert simplicity here
and cite the work. Classical source: J. H. Conway, *A perfect group of order
8,315,553,613,086,720,000 and the sporadic simple groups* (1968); Conway &
Sloane, *SPLAG*.

These take `[Group …]` as a hypothesis (the opaque carriers have no derivable
group structure yet), matching the `PSU`/`POmega` pattern in `LieType.lean`. -/
axiom Co1_isSimpleGroup [Group Co1] : IsSimpleGroup Co1
axiom Co2_isSimpleGroup [Group Co2] : IsSimpleGroup Co2
axiom Co3_isSimpleGroup [Group Co3] : IsSimpleGroup Co3

/-! ### Fischer groups -/
opaque Fi22 : Type
opaque Fi23 : Type
opaque Fi24' : Type

/-! ### Monster and Baby Monster + close relatives -/
opaque Monster : Type
opaque BabyMonster : Type
opaque Thompson : Type
opaque HaradaNorton : Type
opaque Held : Type

/-! ### McLaughlin / Suzuki sporadic / Higman-Sims -/
opaque McLaughlin : Type
opaque SuzukiSporadic : Type
opaque HigmanSims : Type

/-! ### Pariahs (not subquotients of the Monster) -/
opaque ONan : Type
opaque Rudvalis : Type
opaque Lyons : Type

/-- Enumeration of the 26 sporadic simple groups by name.

Useful as a concrete Lean object (`Fintype`, `DecidableEq`) for stating
theorems that range over all sporadics, without needing to construct
each group's underlying carrier. -/
inductive Name : Type where
  -- Mathieu (1861-73): the five 4- and 5-transitive groups
  | M11 | M12 | M22 | M23 | M24
  -- Janko (1965-76): J_1, J_3, J_4 are pariahs; J_2 = HJ is in the Happy Family
  | J1 | J2 | J3 | J4
  -- Conway (1968): from automorphisms of the Leech lattice
  | Co1 | Co2 | Co3
  -- Fischer (1971): 3-transposition groups; Fi_24' is the derived subgroup of Fi_24
  | Fi22 | Fi23 | Fi24'
  -- Monster + close relatives (1973-80)
  | Monster | BabyMonster | Thompson | HaradaNorton | Held
  -- McLaughlin / Suzuki sporadic / Higman-Sims
  | McLaughlin | SuzukiSporadic | HigmanSims
  -- The remaining pariahs (O'Nan, Rudvalis, Lyons)
  | ONan | Rudvalis | Lyons
  deriving DecidableEq, Repr, Fintype

/-- There are exactly **26** sporadic simple groups. -/
theorem card_name : Fintype.card Name = 26 := by decide

/-- The 6 **pariahs**: sporadics that are not subquotients of the Monster. -/
def Name.isPariah : Name → Bool
  | .J1 | .J3 | .J4 | .ONan | .Rudvalis | .Lyons => true
  | _ => false

/-- There are exactly **6 pariahs**. -/
theorem card_pariahs : (Finset.univ.filter (fun n : Name => n.isPariah)).card = 6 := by
  decide

/-- The 20 members of the **Happy Family** (subquotients of the Monster). -/
theorem card_happy_family :
    (Finset.univ.filter (fun n : Name => ¬ n.isPariah)).card = 20 := by
  decide

/-- Lookup the underlying opaque carrier type for a sporadic group by name.

Used by `Classification.IsClassified.sporadic` to quantify over sporadics
without enumerating 26 disjuncts inline. Each carrier remains opaque pending
a real construction (Mathieu groups via Steiner systems, Conway groups via the
Leech lattice, Monster via the 196,883-dim representation, etc.).

The explicit `_root_.FiniteSimpleGroups.Sporadics.X` qualification is needed
because the constructor names (`Name.M11`, `Name.J1`, …) shadow the opaque
type names at unqualified resolution inside this namespace. -/
def Name.carrier : Name → Type
  | .M11 => _root_.FiniteSimpleGroups.Sporadics.M11
  | .M12 => _root_.FiniteSimpleGroups.Sporadics.M12
  | .M22 => _root_.FiniteSimpleGroups.Sporadics.M22
  | .M23 => _root_.FiniteSimpleGroups.Sporadics.M23
  | .M24 => _root_.FiniteSimpleGroups.Sporadics.M24
  | .J1  => _root_.FiniteSimpleGroups.Sporadics.J1
  | .J2  => _root_.FiniteSimpleGroups.Sporadics.J2
  | .J3  => _root_.FiniteSimpleGroups.Sporadics.J3
  | .J4  => _root_.FiniteSimpleGroups.Sporadics.J4
  | .Co1 => _root_.FiniteSimpleGroups.Sporadics.Co1
  | .Co2 => _root_.FiniteSimpleGroups.Sporadics.Co2
  | .Co3 => _root_.FiniteSimpleGroups.Sporadics.Co3
  | .Fi22 => _root_.FiniteSimpleGroups.Sporadics.Fi22
  | .Fi23 => _root_.FiniteSimpleGroups.Sporadics.Fi23
  | .Fi24' => _root_.FiniteSimpleGroups.Sporadics.Fi24'
  | .Monster => _root_.FiniteSimpleGroups.Sporadics.Monster
  | .BabyMonster => _root_.FiniteSimpleGroups.Sporadics.BabyMonster
  | .Thompson => _root_.FiniteSimpleGroups.Sporadics.Thompson
  | .HaradaNorton => _root_.FiniteSimpleGroups.Sporadics.HaradaNorton
  | .Held => _root_.FiniteSimpleGroups.Sporadics.Held
  | .McLaughlin => _root_.FiniteSimpleGroups.Sporadics.McLaughlin
  | .SuzukiSporadic => _root_.FiniteSimpleGroups.Sporadics.SuzukiSporadic
  | .HigmanSims => _root_.FiniteSimpleGroups.Sporadics.HigmanSims
  | .ONan => _root_.FiniteSimpleGroups.Sporadics.ONan
  | .Rudvalis => _root_.FiniteSimpleGroups.Sporadics.Rudvalis
  | .Lyons => _root_.FiniteSimpleGroups.Sporadics.Lyons

end Sporadics
end FiniteSimpleGroups
