import Mathlib
import FiniteSimpleGroups.Basic

/-!
# Family 5: The 26 Sporadic Simple Groups

The "leftovers": 26 specific finite simple groups that don't fit any infinite
family. Discovered between 1861 (Mathieu groups) and 1980 (the Monster's
existence proven by Griess).

Twenty of the 26 are **subquotients of the Monster** (`M`) — these are called
the "Happy Family." The remaining 6 are the **Pariahs**: `J_1`, `J_3`, `J_4`,
`O'N`, `Ru`, `Ly`.

## The full list, by discoverer / family

### Mathieu groups (1861-1873) — five

| Group | Order | Acting on |
|-------|-------|-----------|
| `M_11` | 7,920 | 11 points, 4-transitively |
| `M_12` | 95,040 | 12 points, 5-transitively |
| `M_22` | 443,520 | 22 points, 3-transitively |
| `M_23` | 10,200,960 | 23 points, 4-transitively |
| `M_24` | 244,823,040 | 24 points, 5-transitively |

The only 4- and 5-transitive groups other than `S_n`/`A_n`. Mathlib has
**skeletal** work on these in `Mathlib.GroupTheory.SpecificGroups.Mathieu`
(check existence in v4.29.1; often a `sorry`-heavy WIP).

### Janko groups (1965-1976) — four

| Group | Order | Notes |
|-------|-------|-------|
| `J_1` | 175,560 | Janko 1965 — first "new" sporadic after Mathieu, breaking the 92-year drought. **Pariah.** |
| `J_2 = HJ` (Hall-Janko) | 604,800 | Subquotient of Monster. |
| `J_3 = HJM` | 50,232,960 | **Pariah.** |
| `J_4` | ~10^19 (huge) | **Pariah.** |

### Conway groups (1968) — three

| Group | Order | Source |
|-------|-------|--------|
| `Co_1` | ~4 × 10^18 | Automorphisms of Leech lattice / center |
| `Co_2` | 42,305,421,312,000 | Stabilizer of a type-2 vector |
| `Co_3` | 495,766,656,000 | Stabilizer of a type-3 vector |

All from John Conway's work on the Leech lattice (the densest packing of
spheres in 24 dimensions).

### Fischer groups (1971) — three

| Group | Order | Notes |
|-------|-------|-------|
| `Fi_22` | 64,561,751,654,400 | 3-transposition group |
| `Fi_23` | ~4 × 10^18 | 3-transposition group |
| `Fi_24'` | ~1.25 × 10^21 | Derived subgroup of `Fi_24`; the `Fi_24` is itself not simple |

### The Monster and its retinue (1973-1980)

| Group | Order | Discovered by |
|-------|-------|---------------|
| `M` (Monster / Friendly Giant) | ~8 × 10^53 | Fischer-Griess 1973 (conjectured), Griess 1980 (construction) |
| `B` (Baby Monster) | ~4 × 10^33 | Fischer 1973 |
| `Th` (Thompson) | ~9 × 10^16 | Thompson 1976 |
| `HN` (Harada-Norton) | 273,030,912,000,000 | Harada / Norton 1973 |
| `He` (Held) | 4,030,387,200 | Held 1969 |

### Pariahs (full list)

Not subquotients of the Monster:
`J_1` (1965), `J_3` (1976), `J_4` (1976/1980), `O'N` (O'Nan, 1973), `Ru` (Rudvalis, 1973), `Ly` (Lyons, 1972/Sims).

| Group | Order |
|-------|-------|
| `O'N` (O'Nan) | 460,815,505,920 |
| `Ru` (Rudvalis) | 145,926,144,000 |
| `Ly` (Lyons) | ~5 × 10^16 |

### Remaining of the 26: McLaughlin, Suzuki sporadic, Higman-Sims

| Group | Order | Notes |
|-------|-------|-------|
| `McL` (McLaughlin) | 898,128,000 | Subquotient of `Co_1` |
| `Suz` (Suzuki sporadic — **not** the Suzuki Lie-type group) | 448,345,497,600 | |
| `HS` (Higman-Sims) | 44,352,000 | |

## Construction status

Most sporadic groups don't have a clean closed-form construction. They're
typically defined as:
* Stabilizers in a known geometric / combinatorial structure (Leech lattice,
  Steiner system `S(5,8,24)`, the Monster's 196,883-dim representation, etc.)
* Automorphism groups of specific graphs (`HS` from the Higman-Sims graph)
* Subgroups generated by specific matrices acting on specific modules

**Status in mathlib (v4.29.1):** Essentially none of the sporadics are
constructed. This file lists them as opaque types for naming purposes only.
-/

namespace FiniteSimpleGroups
namespace Sporadics

/-! ### Mathieu groups -/
opaque M11 : Type
opaque M12 : Type
opaque M22 : Type
opaque M23 : Type
opaque M24 : Type

/-! ### Janko groups -/
opaque J1 : Type
opaque J2 : Type
opaque J3 : Type
opaque J4 : Type

/-! ### Conway groups -/
opaque Co1 : Type
opaque Co2 : Type
opaque Co3 : Type

/-! #### Conway-group simplicity (axiom, cited)

The Conway groups are the first sporadics in this scaffold to carry an explicit
simplicity claim, seeded by an existing (partial) Lean formalization.

**External evidence.** Erik van der Plas, *Formalisation of the Finite Simple
Conway Groups in Lean*, MSc thesis, Utrecht University, 2024 (advisor
J. M. Commelin).
- Handle: <https://studenttheses.uu.nl/handle/20.500.12932/46756>
- Local PDF: `~/src/lean-refs/papers/conway-groups-lean-thesis.pdf`
- Lean source (mathlib fork): `erikvdplas/mathlib4`,
  `Mathlib/GroupTheory/SpecificGroups/Conway.lean` +
  `Mathlib/GroupTheory/IntegralLattice/Leech/{Basic,Cross}.lean`.
  Local clone: `~/src/lean-refs/conway-vdplas/`.

That work defines `Conway₀ := IntegralLatticeAut Λ` (automorphisms of the Leech
lattice `Λ`) and `Conway₁ := Conway₀ ⧸ center`, and proves simplicity via the
**Iwasawa criterion** — the same engine mathlib uses for `Aₙ`.

**Why axiom, not dependency (decided 2026-05-28).** The formalization is
in-progress: ~18 `sorry`s, including `exists_leech` (the Leech lattice's very
existence) and the `perfect` / `quasipreprimitive` lemmas the `simple` instance
rests on; only `Co0`/`Co1` are touched, `Co2`/`Co3` are untouched. Taking it as
a Lake dependency would launder those `sorry`s into our trusted base — strictly
*less* honest than an explicit, attributed axiom. So we assert simplicity here
and cite the work. Classical source: J. H. Conway, *A perfect group of order
8,315,553,613,086,720,000 and the sporadic simple groups* (1968); Conway &
Sloane, *SPLAG*.

These take `[Group …]` as a hypothesis (the opaque carriers have no derivable
group structure yet), matching the `PSU`/`POmega` pattern in `LieType.lean`. -/
axiom Co1_isSimpleGroup [Group Co1] : IsSimpleGroup Co1
axiom Co2_isSimpleGroup [Group Co2] : IsSimpleGroup Co2
axiom Co3_isSimpleGroup [Group Co3] : IsSimpleGroup Co3

/-! ### Fischer groups -/
opaque Fi22 : Type
opaque Fi23 : Type
opaque Fi24' : Type

/-! ### Monster and Baby Monster + close relatives -/
opaque Monster : Type
opaque BabyMonster : Type
opaque Thompson : Type
opaque HaradaNorton : Type
opaque Held : Type

/-! ### McLaughlin / Suzuki sporadic / Higman-Sims -/
opaque McLaughlin : Type
opaque SuzukiSporadic : Type
opaque HigmanSims : Type

/-! ### Pariahs (not subquotients of the Monster) -/
opaque ONan : Type
opaque Rudvalis : Type
opaque Lyons : Type

/-- Enumeration of the 26 sporadic simple groups by name.

Useful as a concrete Lean object (`Fintype`, `DecidableEq`) for stating
theorems that range over all sporadics, without needing to construct
each group's underlying carrier. -/
inductive Name : Type where
  -- Mathieu (1861-73): the five 4- and 5-transitive groups
  | M11 | M12 | M22 | M23 | M24
  -- Janko (1965-76): J_1, J_3, J_4 are pariahs; J_2 = HJ is in the Happy Family
  | J1 | J2 | J3 | J4
  -- Conway (1968): from automorphisms of the Leech lattice
  | Co1 | Co2 | Co3
  -- Fischer (1971): 3-transposition groups; Fi_24' is the derived subgroup of Fi_24
  | Fi22 | Fi23 | Fi24'
  -- Monster + close relatives (1973-80)
  | Monster | BabyMonster | Thompson | HaradaNorton | Held
  -- McLaughlin / Suzuki sporadic / Higman-Sims
  | McLaughlin | SuzukiSporadic | HigmanSims
  -- The remaining pariahs (O'Nan, Rudvalis, Lyons)
  | ONan | Rudvalis | Lyons
  deriving DecidableEq, Repr, Fintype

/-- There are exactly **26** sporadic simple groups. -/
theorem card_name : Fintype.card Name = 26 := by decide

/-- The 6 **pariahs**: sporadics that are not subquotients of the Monster. -/
def Name.isPariah : Name → Bool
  | .J1 | .J3 | .J4 | .ONan | .Rudvalis | .Lyons => true
  | _ => false

/-- There are exactly **6 pariahs**. -/
theorem card_pariahs : (Finset.univ.filter (fun n : Name => n.isPariah)).card = 6 := by
  decide

/-- The 20 members of the **Happy Family** (subquotients of the Monster). -/
theorem card_happy_family :
    (Finset.univ.filter (fun n : Name => ¬ n.isPariah)).card = 20 := by
  decide

/-- The **order** (number of elements) of each sporadic simple group, as an
ATLAS value written in *factored* form.

**Why factored, not decimal.** The exponents in the prime factorization are far
easier to audit against the ATLAS of Finite Groups than a 54-digit decimal, and
Lean reduces the product to the true `ℕ` either way. So the source-of-truth here
is the exponent vector; the giant decimals (Monster ≈ 8·10⁵³) never have to be
typed correctly.

**Faithfulness status.** Originally reconstructed from memory; now **verified**.
All nine large factorizations (Monster, Baby Monster, J₄, Fi₂₃, Fi₂₄′, Co₁, Th,
Ly, HN) were cross-checked against their canonical ATLAS *decimal* values
(2026-06-03) — see the `order_*_decimal` theorems below, which `decide`-confirm
the factored product equals the published decimal (an independent second
encoding). They are *additionally* over-determined by the sharp index relations
(`order_Co1_eq_98280_mul_Co2`, …) and the subgroup/subquotient divisibility nets,
which pin the uncertain large orders two-sidedly against the high-confidence small
ones. A transposed exponent now breaks at least one machine-checked theorem.
The set of *primes* dividing each order is the cheapest sanity check (e.g. the
15 supersingular primes for the Monster: 2,3,5,7,11,13,17,19,23,29,31,41,47,59,71).

This pins the otherwise-`opaque` carriers: `IsClassified.sporadic` asserts
`Nat.card name.carrier = name.order`, so any eventual construction whose
cardinality disagrees with the ATLAS trips a contradiction. (Order is a complete
fingerprint *among the 26 sporadics* — all 26 are distinct — even though it is
not in general; e.g. `A₈` and `PSL(3,4)` share order 20160.) -/
def Name.order : Name → ℕ
  -- Mathieu
  | .M11 => 2^4 * 3^2 * 5 * 11                                  -- 7,920
  | .M12 => 2^6 * 3^3 * 5 * 11                                  -- 95,040
  | .M22 => 2^7 * 3^2 * 5 * 7 * 11                              -- 443,520
  | .M23 => 2^7 * 3^2 * 5 * 7 * 11 * 23                         -- 10,200,960
  | .M24 => 2^10 * 3^3 * 5 * 7 * 11 * 23                        -- 244,823,040
  -- Janko
  | .J1  => 2^3 * 3 * 5 * 7 * 11 * 19                           -- 175,560
  | .J2  => 2^7 * 3^3 * 5^2 * 7                                 -- 604,800
  | .J3  => 2^7 * 3^5 * 5 * 17 * 19                             -- 50,232,960
  | .J4  => 2^21 * 3^3 * 5 * 7 * 11^3 * 23 * 29 * 31 * 37 * 43  -- ≈ 8.7·10¹⁹
  -- Conway
  | .Co1 => 2^21 * 3^9 * 5^4 * 7^2 * 11 * 13 * 23              -- ≈ 4.2·10¹⁸
  | .Co2 => 2^18 * 3^6 * 5^3 * 7 * 11 * 23                      -- 42,305,421,312,000
  | .Co3 => 2^10 * 3^7 * 5^3 * 7 * 11 * 23                      -- 495,766,656,000
  -- Fischer
  | .Fi22 => 2^17 * 3^9 * 5^2 * 7 * 11 * 13                     -- 64,561,751,654,400
  | .Fi23 => 2^18 * 3^13 * 5^2 * 7 * 11 * 13 * 17 * 23          -- ≈ 4.1·10¹⁸
  | .Fi24' => 2^21 * 3^16 * 5^2 * 7^3 * 11 * 13 * 17 * 23 * 29  -- ≈ 1.3·10²¹
  -- Monster + relatives
  | .Monster =>
      2^46 * 3^20 * 5^9 * 7^6 * 11^2 * 13^3 * 17 * 19 * 23 * 29 * 31 *
        41 * 47 * 59 * 71                                       -- ≈ 8.08·10⁵³
  | .BabyMonster =>
      2^41 * 3^13 * 5^6 * 7^2 * 11 * 13 * 17 * 19 * 23 * 31 * 47 -- ≈ 4.15·10³³
  | .Thompson => 2^15 * 3^10 * 5^3 * 7^2 * 13 * 19 * 31         -- 90,745,943,887,872,000
  | .HaradaNorton => 2^14 * 3^6 * 5^6 * 7 * 11 * 19             -- 273,030,912,000,000
  | .Held => 2^10 * 3^3 * 5^2 * 7^3 * 17                        -- 4,030,387,200
  -- McLaughlin / Suzuki sporadic / Higman-Sims
  | .McLaughlin => 2^7 * 3^6 * 5^3 * 7 * 11                     -- 898,128,000
  | .SuzukiSporadic => 2^13 * 3^7 * 5^2 * 7 * 11 * 13           -- 448,345,497,600
  | .HigmanSims => 2^9 * 3^2 * 5^3 * 7 * 11                     -- 44,352,000
  -- Pariahs (remaining)
  | .ONan => 2^9 * 3^4 * 5 * 7^3 * 11 * 19 * 31                 -- 460,815,505,920
  | .Rudvalis => 2^14 * 3^3 * 5^3 * 7 * 13 * 29                 -- 145,926,144,000
  | .Lyons => 2^8 * 3^7 * 5^6 * 7 * 11 * 31 * 37 * 67           -- ≈ 5.18·10¹⁶

/-- The 26 sporadic orders are pairwise **distinct** — so `Name.order` is a
complete fingerprint among the sporadics, and the `Nat.card = order` pin in
`IsClassified.sporadic` selects a unique name. (Machine-checked: this catches any
collision typo in the table above, though not a wrong-but-still-unique value.) -/
theorem order_injective : Function.Injective Name.order := by decide

/-! ### Internal consistency cross-checks (machine-verified)

The **Mathieu multiple-transitivity stabilizer relations.** `M₁₂`, `M₂₄` act
sharply 5-transitively and `M₁₁`, `M₂₃` 4-transitively on 12 / 24 / 11 / 23
points; in each transitive chain the smaller group is a one-point stabilizer of
the larger, so its index is the number of points: `|M₁₂| = 12·|M₁₁|`,
`|M₂₄| = 24·|M₂₃|`, `|M₂₃| = 23·|M₂₂|`. These are `decide`-checked against the
`Name.order` table — an *independent* cross-check (rooted in the defining
transitivity, not in the listed values) that catches a typo in any one of the
five Mathieu orders, which `order_injective` alone would miss if it kept the
values distinct. (The other 21 sporadics have no such elementary index relation.) -/
theorem order_M12_eq_12_mul_M11 : Name.order .M12 = 12 * Name.order .M11 := by decide
theorem order_M23_eq_23_mul_M22 : Name.order .M23 = 23 * Name.order .M22 := by decide
theorem order_M24_eq_24_mul_M23 : Name.order .M24 = 24 * Name.order .M23 := by decide

/-- **Happy Family ⟹ order divides `|M|`.** Each of the 20 non-pariah sporadics is a
*subquotient* of the Monster (`H = A/B` with `B ⊴ A ≤ M`), so `|H| = |A|/|B|` divides `|M|`.
This `decide`-checks all 20 Happy-Family orders against `Name.order .Monster` at once — the
strongest single consistency net on the table, since it tests the Monster's (largest, least
certain) order against 20 independent values. The 6 pariahs are excluded precisely because they
are *not* Monster subquotients, so no such divisibility is asserted for them. -/
theorem happyFamily_order_dvd_monster :
    ∀ n : Name, ¬ n.isPariah → n.order ∣ Name.order .Monster := by decide

/-- The **subquotients of `Co₁`** among the sporadics: the "second generation" of
the Happy Family (the Leech-lattice groups), together with the first-generation
Mathieu groups. Each is a subquotient of `Co₁` (equivalently of `Co₀ = 2·Co₁`,
the automorphism group of the Leech lattice), so its order divides `|Co₁|`.

**Membership** (Robert Wilson's "three generations" organization of the Happy
Family): the Conway groups `Co₂`, `Co₃`; the Leech-lattice sporadics
`Suz`, `McL`, `HS`, and `J₂` (Hall-Janko); and the Mathieu groups
`M₁₁, M₁₂, M₂₂, M₂₃, M₂₄` (the first generation, themselves subquotients of the
second). Confidence ≈ 90% on this membership list — `J₂`'s inclusion (via
`J₂ < G₂(4) < Suz`) is the least-certain edge; everything else is a textbook
Leech-lattice stabilizer chain. The *divisibility* consequence is `decide`-checked
below and so is independent of any membership error: a wrong member that failed to
divide would simply not compile. -/
def Name.isCo1Subquotient : Name → Bool
  | .Co2 | .Co3 | .SuzukiSporadic | .McLaughlin | .HigmanSims | .J2
  | .M11 | .M12 | .M22 | .M23 | .M24 => true
  | _ => false

/-- There are **11** sporadic subquotients of `Co₁` (excluding `Co₁` itself). -/
theorem card_co1_subquotients :
    (Finset.univ.filter (fun n : Name => n.isCo1Subquotient)).card = 11 := by decide

/-- **Co₁ subquotients ⟹ order divides `|Co₁|`.** Each of the 11 sporadics above is
a subquotient of `Co₁`, so (`|H| = |A|/|B|` for `B ⊴ A ≤ Co₁`) its order divides
`Name.order .Co1`. This `decide`-checks the table's *second*-largest uncertain value
(`Co₁ ≈ 4.2·10¹⁸`) against 11 independent smaller orders at once — the analogue of
`happyFamily_order_dvd_monster` one rung down the subquotient lattice. Catches a
transposed exponent in `Co₁` (or in any of the 11) that `order_injective` would miss.
The Conway simplicity axioms (`Co{1,2,3}_isSimpleGroup`) are unrelated; this is a
pure arithmetic consistency test on the order table. -/
theorem co1Subquotient_order_dvd_co1 :
    ∀ n : Name, n.isCo1Subquotient → n.order ∣ Name.order .Co1 := by decide

/-! ### Sharp index cross-checks — pinning the *uncertain* orders two-sidedly

The divisibility nets above (`happyFamily_order_dvd_monster`,
`co1Subquotient_order_dvd_co1`) only bound the large orders **from below**: a
transposed exponent that *increased* `|Monster|` or `|Co₁|` would still pass,
because divisibility `h ∣ G` only needs `vₚ(h) ≤ vₚ(G)`. The relations here are
**exact index equalities `|G| = k·|H|`** with `k` supplied from an *independent*
geometric/combinatorial fact (not read off the order table), so they pin the
larger order from **both** sides against a smaller, higher-confidence one. -/

/-- **`|Co₁| = 98280·|Co₂|`.** `Co₂` is the stabilizer in `Co₀ = 2·Co₁` (the
automorphism group of the Leech lattice `Λ`) of a fixed **type-2** vector (a
minimal vector, norm 4). `Λ` has exactly **196560** type-2 vectors in a single
`Co₀`-orbit, and `−1 ∈ Co₀` moves each (`−v ≠ v`), so `Co₂` injects into
`Co₁ = Co₀/⟨−1⟩` with index `196560/2 = 98280`. The constant `98280` comes from
the Leech minimal-vector count, *not* from the order table, so this `decide`
two-sidedly pins the least-certain `|Co₁|` against the more-certain `|Co₂|`. -/
theorem order_Co1_eq_98280_mul_Co2 :
    Name.order .Co1 = 98280 * Name.order .Co2 := by decide

/-- **`|Co₁| = 8386560·|Co₃|`.** `Co₃` is the `Co₀`-stabilizer of a fixed
**type-3** vector (norm 6); `Λ` has exactly **16773120** of them in one orbit,
giving index `16773120/2 = 8386560` in `Co₁` (same `⟨−1⟩` argument as above).
Independent geometric constant ⇒ a second two-sided pin on `|Co₁|`. -/
theorem order_Co1_eq_8386560_mul_Co3 :
    Name.order .Co1 = 8386560 * Name.order .Co3 := by decide

/-- **`|Co₃| = 552·|McL|`.** `Co₃` has a rank-3 permutation action on **276**
points (the vertices of the McLaughlin geometry plus a point) with point
stabilizer `McL:2`, so `|Co₃| = 276·|McL:2| = 276·2·|McL| = 552·|McL|`. The
point count `276` is independent of the table; chained with
`order_Co1_eq_8386560_mul_Co3` this pins `|Co₁|` transitively against the
high-confidence `|McL|`. -/
theorem order_Co3_eq_552_mul_McL :
    Name.order .Co3 = 552 * Name.order .McLaughlin := by decide

/-! ### Subgroup-tower divisibility cross-checks

Each relation below is `H ≤ G` for a *named* maximal or point-stabilizer
subgroup (an independent group-theoretic fact), tested as `|H| ∣ |G|`. Unlike a
coincidental numerical divisibility, every one corresponds to a real containment
in the ATLAS, so it is a faithful consistency probe of the two orders. -/

/-- **Mathieu subgroup tower.** Witt's chain of point-stabilizer / maximal
subgroups: `M₁₁ ≤ M₁₂`, `M₁₂ ≤ M₂₄` (as `M₁₂:2`), `M₁₁ ≤ M₂₃` (maximal, index
1288), `M₂₂ ≤ M₂₃ ≤ M₂₄` (one-point stabilizers). Each forces a divisibility,
`decide`-checked here; together with the sharp transitivity relations
(`order_M12_eq_12_mul_M11` etc.) this over-determines the five Mathieu orders. -/
theorem mathieu_tower_dvd :
    Name.order .M11 ∣ Name.order .M12 ∧
    Name.order .M12 ∣ Name.order .M24 ∧
    Name.order .M11 ∣ Name.order .M23 ∧
    Name.order .M22 ∣ Name.order .M23 ∧
    Name.order .M23 ∣ Name.order .M24 := by decide

/-- **Fischer 3-transposition tower.** `Fi₂₂` is a subquotient of `Fi₂₃` (its
transposition centralizer is `2·Fi₂₂`), and `Fi₂₃` likewise of `Fi₂₄′`, so
`|Fi₂₂| ∣ |Fi₂₃| ∣ |Fi₂₄′|`. This pins the two large, less-certain Fischer orders
*from below* against the higher-confidence `|Fi₂₂|`. -/
theorem fischer_tower_dvd :
    Name.order .Fi22 ∣ Name.order .Fi23 ∧
    Name.order .Fi23 ∣ Name.order .Fi24' := by decide

/-! ### Canonical-decimal cross-checks (ATLAS)

The nine factorizations the order docstring flags at ~85% confidence, each
asserted equal to its **canonical decimal value** as published in the ATLAS of
Finite Groups / the standard references. The decimal is an *independent second
encoding* of the same number (memorised/typed separately from the exponent
vector), so any single transposed exponent in `Name.order` changes the product
and trips one of these equalities. (Verified against the canonical values
2026-06-03; this discharges the cross-check requested in
`RFI-ATLAS-sporadic-orders.md`.) -/
theorem order_Monster_decimal :
    Name.order .Monster = 808017424794512875886459904961710757005754368000000000 := by decide
theorem order_BabyMonster_decimal :
    Name.order .BabyMonster = 4154781481226426191177580544000000 := by decide
theorem order_J4_decimal :
    Name.order .J4 = 86775571046077562880 := by decide
theorem order_Co1_decimal :
    Name.order .Co1 = 4157776806543360000 := by decide
theorem order_Fi23_decimal :
    Name.order .Fi23 = 4089470473293004800 := by decide
theorem order_Fi24'_decimal :
    Name.order .Fi24' = 1255205709190661721292800 := by decide
theorem order_Thompson_decimal :
    Name.order .Thompson = 90745943887872000 := by decide
theorem order_Lyons_decimal :
    Name.order .Lyons = 51765179004000000 := by decide
theorem order_HaradaNorton_decimal :
    Name.order .HaradaNorton = 273030912000000 := by decide

/-- Lookup the underlying opaque carrier type for a sporadic group by name.

Used by `Classification.IsClassified.sporadic` to quantify over sporadics
without enumerating 26 disjuncts inline. Each carrier remains opaque pending
a real construction (Mathieu groups via Steiner systems, Conway groups via the
Leech lattice, Monster via the 196,883-dim representation, etc.).

The explicit `_root_.FiniteSimpleGroups.Sporadics.X` qualification is needed
because the constructor names (`Name.M11`, `Name.J1`, …) shadow the opaque
type names at unqualified resolution inside this namespace. -/
def Name.carrier : Name → Type
  | .M11 => _root_.FiniteSimpleGroups.Sporadics.M11
  | .M12 => _root_.FiniteSimpleGroups.Sporadics.M12
  | .M22 => _root_.FiniteSimpleGroups.Sporadics.M22
  | .M23 => _root_.FiniteSimpleGroups.Sporadics.M23
  | .M24 => _root_.FiniteSimpleGroups.Sporadics.M24
  | .J1  => _root_.FiniteSimpleGroups.Sporadics.J1
  | .J2  => _root_.FiniteSimpleGroups.Sporadics.J2
  | .J3  => _root_.FiniteSimpleGroups.Sporadics.J3
  | .J4  => _root_.FiniteSimpleGroups.Sporadics.J4
  | .Co1 => _root_.FiniteSimpleGroups.Sporadics.Co1
  | .Co2 => _root_.FiniteSimpleGroups.Sporadics.Co2
  | .Co3 => _root_.FiniteSimpleGroups.Sporadics.Co3
  | .Fi22 => _root_.FiniteSimpleGroups.Sporadics.Fi22
  | .Fi23 => _root_.FiniteSimpleGroups.Sporadics.Fi23
  | .Fi24' => _root_.FiniteSimpleGroups.Sporadics.Fi24'
  | .Monster => _root_.FiniteSimpleGroups.Sporadics.Monster
  | .BabyMonster => _root_.FiniteSimpleGroups.Sporadics.BabyMonster
  | .Thompson => _root_.FiniteSimpleGroups.Sporadics.Thompson
  | .HaradaNorton => _root_.FiniteSimpleGroups.Sporadics.HaradaNorton
  | .Held => _root_.FiniteSimpleGroups.Sporadics.Held
  | .McLaughlin => _root_.FiniteSimpleGroups.Sporadics.McLaughlin
  | .SuzukiSporadic => _root_.FiniteSimpleGroups.Sporadics.SuzukiSporadic
  | .HigmanSims => _root_.FiniteSimpleGroups.Sporadics.HigmanSims
  | .ONan => _root_.FiniteSimpleGroups.Sporadics.ONan
  | .Rudvalis => _root_.FiniteSimpleGroups.Sporadics.Rudvalis
  | .Lyons => _root_.FiniteSimpleGroups.Sporadics.Lyons

end Sporadics
end FiniteSimpleGroups
